name: Build Mac
run-name: Build Mac ${{ inputs.branch }}-${{ inputs.profile }}-${{ inputs.version_name }}-${{ inputs.version_code }}
on:
  workflow_call:
    inputs:
      changelog:
        description: 'Changelog'
        required: false
        type: string

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: build
        run: |
          extra_args=$(echo "{}" | jq '. += {changelog: "${{ inputs.changelog }}"}')
          ./test.sh -x "$extra_args"
