# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      fetch_localization:
        description: 'Fetch Localization'
        required: false
        type: boolean
      fetch_config:
        description: 'Fetch Config'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          clean: false

      # Runs a single command using the runners shell
      - name: Check ENV
        run: env
      - run: |
          echo "Localization: $LOCALIZATION"
          echo "Config: $CONFIG"
          echo "Environment: $ENVIRONMENT"
        env:
          LOCALIZATION: ${{ inputs.fetch_localization }}
          CONFIG: ${{ inputs.fetch_config }}
          ENVIRONMENT: ${{ inputs.environment }}

      # Runs a set of commands using the runners shell
      - name: Run test shell
        run: |
          chmod +x ${GITHUB_WORKSPACE}/test.sh
          ${GITHUB_WORKSPACE}/test.sh ${{ github.run_number }}
